### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by Enerccio** [cheako/os-prober#17]
I am trying to install third linux manually (mount partition, copy over files, copy linux and chroot and create mkinitcpio initramfs) but os-prober will detect this new linux as old linux because apparently it tries to parse my custom rule for creating grub entires for this new linux I put in /etc/grub.d and lists them as result of search, which makes no sense. 

Os prober correctly lists windows at /dev/sda2 and debian (old linux) in /dev/sda5 but 

`linux-boot-probe /dev/sda5` will lists my new os that was read from /etc/grub.d/35_clone script that was mounted on /dev/sda7/etc/grub.d/35_clone (because /dev/sda7 is root when I am chrooted in new linux). Shouldn't `linux-boot-probe` read /dev/sda5/etc/grub.d/* instead of /etc/grub.d/* ? ?? Am I missing something?

`partition="$1"`
`bootpart="$2"`
`mpoint="$3"`
`type="$4"`

are correct yet it will still read /etc/grub.d/* instead of /dev/sda5/etc/grub.d/* files...

Result of os-prober
[prober.out.txt](https://github.com/cheako/os-prober/files/2284378/prober.out.txt)

Results of linux-boot-prober with set -x
[boot-prober.err.txt](https://github.com/cheako/os-prober/files/2284375/boot-prober.err.txt)
[boot-prober.out.txt](https://github.com/cheako/os-prober/files/2284376/boot-prober.out.txt)

Mounts
[mnt.out.txt](https://github.com/cheako/os-prober/files/2284377/mnt.out.txt)

This configuration it should read when reading /dev/sda5
[devsda5.zip](https://github.com/cheako/os-prober/files/2284388/devsda5.zip)

This configuration it should not read when reading /dev/sda5 since it's from /dev/sda7 ...
[devsda7.zip](https://github.com/cheako/os-prober/files/2284389/devsda7.zip)

**Comment by cheako** [comment]
This is perhaps the wrong place to ask for support. I started this repo for extending os-prober to support subvolums.
